<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.0.2</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>
	<groupId>org.modelio</groupId>
	<artifactId>org.modelio.foodity</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>org.modelio.foodity</name>
	<description>Foodity backend project</description>
	<properties>
		<java.version>17</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-elasticsearch</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<!-- https://mvnrepository.com/artifact/co.elastic.clients/elasticsearch-java -->
		<dependency>
			<groupId>co.elastic.clients</groupId>
			<artifactId>elasticsearch-java</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<!-- Swagger UI -->
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
			<version>2.0.0</version>
		</dependency>
<!--		<dependency>-->
<!--			<groupId>com.fasterxml.jackson.dataformat</groupId>-->
<!--			<artifactId>jackson-dataformat-csv</artifactId>-->
<!--			<version>2.14.1</version>-->
<!--		</dependency>-->
		<dependency>
			<groupId>com.opencsv</groupId>
			<artifactId>opencsv</artifactId>
			<version>5.5.2</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.postgresql/postgresql -->
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<scope>runtime</scope>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.hibernate/hibernate-validator -->
		<dependency>
		    <groupId>org.hibernate</groupId>
		    <artifactId>hibernate-validator</artifactId>
		    <version>8.0.0.Final</version>
		</dependency>
		<dependency>
		    <groupId>com.h2database</groupId>
		    <artifactId>h2</artifactId>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-jackson</artifactId>
			<version>0.11.5</version>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-api</artifactId>
			<version>0.11.5</version>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-impl</artifactId>
			<version>0.11.5</version>
		</dependency>
		<dependency>
		    <groupId>org.mapstruct</groupId>
		    <artifactId>mapstruct</artifactId>
		    <version>1.5.3.Final</version> 
		</dependency>
		<dependency>
	        <groupId>org.springframework.boot</groupId>
	        <artifactId>spring-boot-starter-mail</artifactId>
	    </dependency>
	    <!-- ProxyU Java SDK-->
		<dependency>
			<groupId>com.jibecompany</groupId>
			<artifactId>proxyu-java-client</artifactId>
			<version>0.0.4</version>
		</dependency>
		<dependency>
		    <groupId>org.liquibase</groupId>
		    <artifactId>liquibase-core</artifactId>
		    <version>4.17.2</version>
		</dependency>
		<dependency>
			<groupId>com.googlecode.libphonenumber</groupId>
			<artifactId>libphonenumber</artifactId>
			<version>8.13.47</version>
		</dependency>
		<dependency>
			<groupId>io.searchbox</groupId>
			<artifactId>jest</artifactId>
			<version>6.3.0</version>
		</dependency>
		<dependency>
		    <groupId>org.json</groupId>
		    <artifactId>json</artifactId>
		    <version>20240205</version>
		</dependency>
		<dependency>
		    <groupId>fi.solita.clamav</groupId>
		    <artifactId>clamav-client</artifactId>
		    <version>1.0.0</version>
		</dependency>

	</dependencies>
	<repositories>
		<repository>
			<id>local_for_jibe</id>
			<name>In Project Repo</name>
			<url>file://${basedir}/../repository</url>
		</repository>
		<repository>
			<id>maven_doca</id>
			<name>Maven proxy Docaposte</name>
			<url>https://outils.docapost.tech/nexus/repository/central/</url>
    	</repository>
	</repositories>
	<profiles>
		<profile>
			<id>dev</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<properties>
				<build.profile.id>dev</build.profile.id>
				<profileActive>dev</profileActive>
			</properties>
		</profile>
		<profile>
			<id>preProd</id>
			<properties>
				<build.profile.id>preProd</build.profile.id>
				<profileActive>preProd</profileActive>
			</properties>
		</profile>
		<profile>
			<id>prod</id>
			<properties>
				<build.profile.id>prod</build.profile.id>
				<profileActive>prod</profileActive>
			</properties>
		</profile>
	</profiles>
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.pitest</groupId>
				<artifactId>pitest-maven</artifactId>
				<version>1.15.8</version>
				<dependencies>
					<dependency>
						<groupId>org.pitest</groupId>
						<artifactId>pitest-junit5-plugin</artifactId>
						<version>1.2.1</version>
					</dependency>
				</dependencies>
				<configuration>
					<targetClasses>
						<param>org.eclipse.foodity.elasticsearch.service.PersonalDataCheckService</param>
					</targetClasses>
					<targetTests>
						<param>org.eclipse.foodity.elasticsearch.service.PersonalDataCheckService*Test</param>
					</targetTests>
					<outputFormats>
						<param>HTML</param>
						<param>XML</param>
					</outputFormats>
					<timestampedReports>false</timestampedReports>
				</configuration>
			</plugin>
			<plugin>
			    <groupId>org.apache.maven.plugins</groupId>
			    <artifactId>maven-compiler-plugin</artifactId>
			    <configuration>
			        <source>17</source>
			        <target>17</target>
			        <annotationProcessorPaths>
			            <path>
							<groupId>org.projectlombok</groupId>
			                <artifactId>lombok</artifactId>
			                <version>1.18.26</version>
						</path>
			            <path>
			                <groupId>org.mapstruct</groupId>
			                <artifactId>mapstruct-processor</artifactId>
			                <version>1.5.3.Final</version>
			            </path>
			        </annotationProcessorPaths>
			        <compilerArgs>
						-Amapstruct.defaultComponentModel=spring
					</compilerArgs>
			    </configuration>
			</plugin>
			<plugin>
		        <groupId>org.liquibase</groupId>
		        <artifactId>liquibase-maven-plugin</artifactId>
		        <executions>
		        	<execution>
		            	<phase>process-resources</phase>
		            </execution>
		        </executions>
		       <configuration>
				    <changeLogFile>db.changelog/db.changelog-master.xml</changeLogFile>
				    <url>jdbc:mysql://localhost:3306/Foodity?serverTimezone=UTC</url>
				    <username>root</username>
				    <password></password>
				    <driver>com.mysql.cj.jdbc.Driver</driver>
			    </configuration>
			    <dependencies>
	                <dependency>
	                    <groupId>javax.xml.bind</groupId>
	                    <artifactId>jaxb-api</artifactId>
	                    <version>2.3.1</version>
	                </dependency>
                </dependencies>
			</plugin>
		</plugins>
	</build>
</project>
